spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/news_service
    driver-class-name: org.postgresql.Driver

    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace

logging:
  level:
    com:
      p6spy:
        engine:
          spy: DEBUG
security:
  ignored: /**